### PR TITLE
Expose CopyOptions in ArchiveEntry.extract().

### LINKED ISSUE #18: Change of behavior between jarchivelib and compress4j
Hi,

Thank you for taking on the development of this library and supporting it.

I recently switched from jarchivelib to compress4j due to the vulnerability warnings for one of my projects. After doing that, I noticed that I now get an exception for Windows machines when extracting a file to a folder in which some of the files already exist.

This led me to propose #17.

Reverting to jarchivelib or using the change proposed in #17 along with `StandardCopyOption.REPLACE_EXISTING` seems to fix the issue for now.

Here is the stack trace using the latest available version of compress4j:

```java
java.nio.file.FileAlreadyExistsException: C:\Users\username\Documents\fresh-install-1900\folder\file.txt
	at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:87)
	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108)
	at java.base/sun.nio.fs.WindowsFileSystemProvider.newByteChannel(WindowsFileSystemProvider.java:236)
	at java.base/java.nio.file.spi.FileSystemProvider.newOutputStream(FileSystemProvider.java:484)
	at java.base/java.nio.file.Files.newOutputStream(Files.java:228)
	at java.base/java.nio.file.Files.copy(Files.java:3160)
	at io.github.compress4j.archivers.IOUtils.copy(IOUtils.java:68)
	at io.github.compress4j.archivers.CommonsArchiveEntry.extract(CommonsArchiveEntry.java:65)
	... <other unrelated parts of the stack>
```

### PR DESCRIPTION
**Pull request by hhslepicka**
Thank you for moving forward with the maintenance of `jarchivelib`.

While using the library, I discovered the need to replace existing files while extracting an archive.
This PR allows me to pass options to the Files.copy.

Closes #18

### CODE REVIEW

**Comment by austek** [comment]
Could you provide a unit test please

**Comment by hhslepicka** [comment]
@austek I will try to come up with unit test for the cases highlighted here soon. Thank you for taking a look into it.

**Comment by hhslepicka** [comment]
@austek, sorry for the delay. I added tests for the changes and tests are passing locally.

**Comment by hhslepicka** [comment]
@austek thank you for approving the CI execution.
The error is now unrelated to the changes.
```
FAILURE: Build failed with an exception.
> Task :sonar FAILED

* What went wrong:
Execution failed for task ':sonar'.
> Project not found. Please check the 'sonar.projectKey' and 'sonar.organization' properties, the 'SONAR_TOKEN' environment variable, or contact the project administrator to check the permissions of the user the token belongs to
```

Since I am an outside contributor the `SONAR_TOKEN` secret is not passed to the pipeline which causes the failure above.

**Review by austek — APPROVED** [review]

**Comment by austek** [comment]
handled by #19

**Pull request closed without merging**
